/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_HANDTRACKING_ROBOT_PB_H_INCLUDED
#define PB_HANDTRACKING_ROBOT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _handtracking_HandData {
    double timestamp;
    float x;
    float y;
    float z;
    float openness;
    float pitch;
} handtracking_HandData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define handtracking_HandData_init_default       {0, 0, 0, 0, 0, 0}
#define handtracking_HandData_init_zero          {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define handtracking_HandData_timestamp_tag      1
#define handtracking_HandData_x_tag              2
#define handtracking_HandData_y_tag              3
#define handtracking_HandData_z_tag              4
#define handtracking_HandData_openness_tag       5
#define handtracking_HandData_pitch_tag          6

/* Struct field encoding specification for nanopb */
#define handtracking_HandData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   timestamp,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    openness,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             6)
#define handtracking_HandData_CALLBACK NULL
#define handtracking_HandData_DEFAULT NULL

extern const pb_msgdesc_t handtracking_HandData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define handtracking_HandData_fields &handtracking_HandData_msg

/* Maximum encoded size of messages (where known) */
#define HANDTRACKING_ROBOT_PB_H_MAX_SIZE         handtracking_HandData_size
#define handtracking_HandData_size               34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
